//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long IdOrderItem { get; set; }
        public Nullable<long> IdOrder { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public Nullable<int> QuantityOrderItem { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
